# Generated by Django 5.0.1 on 2024-07-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_libro_editorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default='Descripción no disponible'),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='Desconocida', max_length=200),
        ),
    ]
